Repository Horizons-Games/Axolotl-Engine, pull requests merged in 2023-08, with the labels that each got.

#520 feat: limit number of console lines drawn
  Source/DataModels/Windows/EditorWindows/WindowConsole.cpp
  Source/DataModels/Windows/EditorWindows/WindowConsole.h
Labels: qol

#618 Feat [Gameplay]: Light finisher attack
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewBixPrefab.axolotl
  Game/Scripts/LightAttackBullet.cpp
  Game/Scripts/LightAttackBullet.h
  Game/Scripts/LightFinisherAttackScript.cpp
  Game/Scripts/LightFinisherAttackScript.h
  Game/Scripts/RangedFastAttackBullet.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay

#613 fix: bloom appears on the left border
  Source/Modules/ModuleRender.cpp
Labels: bug, graphics

#611 feat: Trail
  Game/Assets/Scenes/TrailTest.axolotl
  Game/Assets/Textures/swoosh00.png
  Source/DataModels/Camera/Camera.h
  Source/DataModels/Components/Component.h
  Source/DataModels/Components/ComponentTrail.cpp
  Source/DataModels/Components/ComponentTrail.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/GameObject/GameObject.h
  Source/DataModels/ParticleSystem/EmitterInstance.h
  Source/DataModels/ParticleSystem/ModuleBase.h
  Source/DataModels/ParticleSystem/ModuleColor.h
  Source/DataModels/ParticleSystem/ModulePosition.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.h
  Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowTrailTexture.cpp
  Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowTrailTexture.h
  Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
  Source/DataModels/Windows/EditorWindows/WindowInspector.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/ComponentWindow.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Enums/BlendingType.h
  Source/Enums/ComponentType.h
  Source/FileSystem/Importers/ParticleSystemImporter.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Shaders/Common/Functions/pbr_functions.glsl
  Source/Shaders/Common/Functions/srgba_functions.glsl
  Source/Shaders/color_correction_fragment.glsl
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/gBuffer_Metallic_fs.glsl
  Source/Shaders/gBuffer_Specular_fs.glsl
  Source/Shaders/metallic_fragment.glsl
  Source/Shaders/skybox_fragment.glsl
  Source/Shaders/specular_fragment.glsl
  Source/Shaders/trail_fragment.glsl
  Source/Shaders/trail_vertex.glsl
Labels: graphics

#626 Feat: Heavy Finisher Attack
  Game/Assets/Materials/LightSaberLightSaber.001_0.mat
  Game/Assets/Materials/LightSaberLightSaber.001_0.mat.meta
  Game/Assets/Materials/LightSaberLightSaberEmission_1.mat
  Game/Assets/Materials/LightSaberLightSaberEmission_1.mat.meta
  Game/Assets/Meshes/LightSaber.Mesh.003_0.mesh
  Game/Assets/Meshes/LightSaber.Mesh.003_0.mesh.meta
  Game/Assets/Meshes/LightSaber.Mesh.003_1.mesh
  Game/Assets/Meshes/LightSaber.Mesh.003_1.mesh.meta
  Game/Assets/Models/LightSaber.fbx
  Game/Assets/Models/LightSaber.fbx.meta
  Game/Assets/ParticleSystem/NewSpark1.particle
  Game/Assets/Scenes/BixPrefab.axolotl
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/HeavyFinisherAttack.cpp
  Game/Scripts/HeavyFinisherAttack.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay

#630 Fix: Enemy Detection
  Game/Assets/ParticleSystem/DetectParticle.particle
  Game/Assets/ParticleSystem/DetectParticle.particle.meta
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Assets/Scenes/NewVenomitePrefab.axolotl
  Game/Assets/Textures/Target.png
  Game/Assets/Textures/Target.png.meta
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/ComboManager.cpp
  Game/Scripts/ComboManager.h
  Game/Scripts/EnemyClass.cpp
  Game/Scripts/EnemyClass.h
  Game/Scripts/EntityDetection.cpp
  Game/Scripts/EntityDetection.h
  Source/DataModels/ParticleSystem/ParticleEmitter.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentParticle.cpp
Labels: gameplay

#615 feat: improve dash
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/GameplayFullTrial_Without_enemies.axolotl
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/ComboManager.cpp
  Game/Scripts/ComboManager.h
  Game/Scripts/DebugGame.cpp
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/HealthSystem.h
  Game/Scripts/JumpFinisherArea.cpp
  Game/Scripts/PlayerJumpScript.cpp
  Game/Scripts/PlayerJumpScript.h
  Game/Scripts/PlayerManagerScript.cpp
  Game/Scripts/PlayerManagerScript.h
  Game/Scripts/PlayerMoveScript.cpp
  Game/Scripts/PlayerMoveScript.h
  Game/Scripts/PlayerRotationScript.cpp
  Game/Scripts/PlayerRotationScript.h
  Game/Scripts/PowerUpLogicScript.cpp
  Source/DataModels/Windows/EditorWindows/WindowConfiguration.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform2D.cpp
  Source/DataModels/Windows/SubWindows/WindowInput.cpp
  Source/DataModels/Windows/SubWindows/WindowInput.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay

#632 feat: merge together all the combat
  Game/Assets/Animation/BixFinalAnimations.Armature_SingleJumpAttack.anim
  Game/Assets/Animation/BixFinalAnimations.Armature_SingleJumpAttack.anim.meta
  Game/Assets/ParticleSystem/JumpFinisherAreaParticles.particle
  Game/Assets/ParticleSystem/JumpFinisherAreaParticles.particle.meta
  Game/Assets/ParticleSystem/LightFinisherBulletParticles.particle
  Game/Assets/ParticleSystem/LightFinisherBulletParticles.particle.meta
  Game/Assets/Scenes/BixPrefab.axolotl
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Assets/Scenes/NewVenomitePrefab.axolotl
  Game/Assets/StateMachine/BixAnimController.state
  Game/Assets/StateMachine/BixAnimController.state.meta
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/CantinaNPCAnimationManager.cpp
  Game/Scripts/ComboManager.cpp
  Game/Scripts/ComboManager.h
  Game/Scripts/EntityDetection.cpp
  Game/Scripts/EntityDetection.h
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/HealthSystem.h
  Game/Scripts/JumpFinisherArea.cpp
  Game/Scripts/JumpFinisherArea.h
  Game/Scripts/JumpFinisherAttack.cpp
  Game/Scripts/JumpFinisherAttack.h
  Game/Scripts/JumpFinisherAttackBullet.cpp
  Game/Scripts/JumpFinisherAttackBullet.h
  Game/Scripts/LightAttackBullet.cpp
  Game/Scripts/LightAttackBullet.h
  Game/Scripts/LightFinisherAttackScript.cpp
  Game/Scripts/LightFinisherAttackScript.h
  Game/Scripts/PlayerDeathScript.cpp
  Game/Scripts/PlayerJumpScript.cpp
  Game/Scripts/PlayerJumpScript.h
  Game/Scripts/PlayerMoveScript.cpp
  Game/Scripts/UIComboManager.cpp
  Game/Scripts/UIComboManager.h
  Source/DataModels/Components/ComponentAnimation.cpp
  Source/DataModels/Components/ComponentAnimation.h
Labels: gameplay

#634 fix[WIP]: diagonal dash
  Game/Scripts/PlayerMoveScript.cpp
Labels: gameplay

#625 perf[particles]: Particles only updated when inside the frustum
  Game/Assets/ParticleSystem/TestParticles.particle
  Game/Assets/ParticleSystem/TestParticles.particle.meta
  Game/Assets/Textures/Target.png
  Game/Assets/Textures/Target.png.meta
  Source/DataModels/Components/ComponentParticleSystem.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.h
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleColor.cpp
  Source/DataModels/ParticleSystem/ModulePosition.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/ParticleSystem/ModuleRotation.cpp
  Source/DataModels/ParticleSystem/ModuleSize.cpp
  Source/DataModels/ParticleSystem/ModuleSpawn.cpp
  Source/DataModels/ParticleSystem/ModuleSpawn.h
  Source/DataModels/ParticleSystem/ParticleEmitter.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentParticle.cpp
Labels: graphics

#624 feat: bloom modificable for each material
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Batch/GeometryBatch.h
  Source/DataModels/Resources/ResourceMaterial.cpp
  Source/DataModels/Resources/ResourceMaterial.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp
  Source/Shaders/color_correction_fragment.glsl
  Source/Shaders/gBuffer_Metallic_fs.glsl
  Source/Shaders/gBuffer_Specular_fs.glsl
Labels: graphics

#638 feat[shadows]: Added Shadow Mapping
  Game/Assets/Scenes/[DO NOT DELETE]Graphics testing.axolotl
  Game/Assets/Scenes/highlighting_test.axolotl
  Source/DataModels/Batch/BatchManager.cpp
  Source/DataModels/Batch/BatchManager.h
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Batch/GeometryBatch.h
  Source/DataModels/Camera/CameraDefines.h
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/Components/ComponentDirLight.h
  Source/DataModels/GBuffer/GBuffer.cpp
  Source/DataModels/GBuffer/GBuffer.h
  Source/DataModels/Program/Program.cpp
  Source/DataModels/Program/Program.h
  Source/DataModels/Resources/ResourceMaterial.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
  Source/DataModels/Windows/SubWindows/WindowCamera.cpp
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/min_max.glsl
  Source/Shaders/parallel_reduction.glsl
  Source/Shaders/shadow_map_fragment.glsl
  Source/Shaders/shadow_map_vertex.glsl
Labels: graphics

#643 fix: jump attack transition
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/PlayerJumpScript.cpp
Labels: gameplay

#637 Feat: Attack Movement Improvement
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/PlayerMoveScript.cpp
  Game/Scripts/PlayerMoveScript.h
Labels: gameplay

#656 fix: bloom
  Source/Modules/ModuleRender.cpp
Labels: bug, graphics

#652 Fix: lights when deleting
  Source/DataModels/Components/ComponentAreaLight.cpp
  Source/DataModels/Components/ComponentLight.cpp
  Source/DataModels/Components/ComponentLight.h
  Source/DataModels/Components/ComponentPointLight.cpp
  Source/DataModels/Components/ComponentSpotLight.cpp
  Source/DataModels/Scene/Scene.cpp
Labels: bug, graphics

#647 feat[animatedTextures]: Added percentage selection in texture to tiling
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Batch/GeometryBatch.h
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/Components/ComponentDirLight.h
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/Resources/ResourceMaterial.cpp
  Source/DataModels/Resources/ResourceMaterial.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp
  Source/Modules/ModuleRender.cpp
  Source/Shaders/gBuffer_Metallic_fs.glsl
  Source/Shaders/gBuffer_Specular_fs.glsl
  Source/Shaders/metallic_fragment.glsl
  Source/Shaders/specular_fragment.glsl
Labels: graphics

#662 feat: Final Boss behaviour, battle and attacks
  Game/Assets/Materials/BossShieldMat.mat
  Game/Assets/Materials/BossShieldMat.mat.meta
  Game/Assets/Scenes/BixPrefab.axolotl
  Game/Assets/Scenes/GameplayFullTrial.axolotl
  Game/Assets/Scenes/GameplayFullTrial_Without_enemies.axolotl
  Game/Assets/Scenes/Gameplay_FinalBoss.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Assets/Scenes/NewVenomitePrefab.axolotl
  Game/Assets/StateMachine/DroneAnimationController.state
  Game/Assets/StateMachine/VenomiteAnimController.state
  Game/Scripts/BossChargeAttackScript.cpp
  Game/Scripts/BossChargeAttackScript.h
  Game/Scripts/BossChargeRockScript.cpp
  Game/Scripts/BossChargeRockScript.h
  Game/Scripts/BossMissilesAttackScript.cpp
  Game/Scripts/BossMissilesAttackScript.h
  Game/Scripts/BossMissilesMissileScript.cpp
  Game/Scripts/BossMissilesMissileScript.h
  Game/Scripts/BossShieldAttackScript.cpp
  Game/Scripts/BossShieldAttackScript.h
  Game/Scripts/BossShieldScript.cpp
  Game/Scripts/BossShieldScript.h
  Game/Scripts/EnemyClass.cpp
  Game/Scripts/EnemyClass.h
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/EnemyDeathScript.h
  Game/Scripts/EnemyDroneScript.cpp
  Game/Scripts/EnemyDroneScript.h
  Game/Scripts/EnemyVenomiteScript.cpp
  Game/Scripts/EnemyVenomiteScript.h
  Game/Scripts/EntityDetection.cpp
  Game/Scripts/FinalBossScript.cpp
  Game/Scripts/FinalBossScript.h
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/MeleeFastAttackBehaviourScript.cpp
  Game/Scripts/MeleeFastAttackBehaviourScript.h
  Game/Scripts/PatrolBehaviourScript.cpp
  Game/Scripts/PatrolBehaviourScript.h
  Game/Scripts/PlayerJumpScript.cpp
  Game/Scripts/PlayerJumpScript.h
  Game/Scripts/PlayerMoveScript.cpp
  Game/Scripts/PlayerMoveScript.h
  Game/Scripts/PowerUpLogicScript.cpp
  Game/Scripts/PowerUpsManagerScript.cpp
  Game/Scripts/PowerUpsManagerScript.h
  Game/Scripts/RangedFastAttackBehaviourScript.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.h
  Game/Scripts/RangedFastAttackBullet.cpp
  Game/Scripts/SeekBehaviourScript.cpp
  Game/Scripts/SeekBehaviourScript.h
  Game/Scripts/ShockWaveAttackAreaScript.cpp
  Game/Scripts/ShockWaveAttackAreaScript.h
  Game/Scripts/ShockWaveAttackScript.cpp
  Game/Scripts/ShockWaveAttackScript.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/PreMades/TemplateSourceScript
Labels: gameplay

#648 feat: capactity to discard meshes and use its diffuseColor, effect damage && create a batch exclusively for Characters
  Game/Assets/Scenes/BixPrefab.axolotl
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Assets/Scenes/NewVenomitePrefab.axolotl
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/HealthSystem.h
  Game/Scripts/MeshEffect.cpp
  Game/Scripts/MeshEffect.h
  Source/DataModels/Batch/BatchManager.cpp
  Source/DataModels/Batch/BatchManager.h
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Batch/GeometryBatch.h
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/Components/ComponentLine.h
  Source/DataModels/Components/ComponentMeshRenderer.cpp
  Source/DataModels/Components/ComponentMeshRenderer.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentMeshRenderer.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Modules/ModuleScene.cpp
  Source/Shaders/Common/Structs/effect.glsl
  Source/Shaders/Common/Structs/tiling.glsl
  Source/Shaders/gBuffer_Metallic_fs.glsl
  Source/Shaders/gBuffer_Specular_fs.glsl
  Source/Shaders/metallic_fragment.glsl
  Source/Shaders/specular_fragment.glsl
Labels: graphics, gameplay

#639 feat: show progress when creating Lib zip file
  Source/Auxiliar/ConnectedCallback.cpp
  Source/Auxiliar/ConnectedCallback.h
  Source/Auxiliar/GameBuilder.cpp
  Source/Auxiliar/GameBuilder.h
  Source/DataModels/Windows/PopUpWindows/WindowLoading.cpp
  Source/DataModels/Windows/PopUpWindows/WindowLoading.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/FileSystem/FileZippedData.h
  Source/FileSystem/ModuleFileSystem.cpp
  Source/FileSystem/ModuleFileSystem.h
  Source/Modules/ModuleEditor.cpp
Labels: qol

#663 feat[graphics]: Variance Shadow Mapping
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Modules/ModuleUI.cpp
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/gaussian_blur.glsl
  Source/Shaders/parallel_reduction.glsl
  Source/Shaders/shadow_depth_variance.glsl
Labels: graphics
