Repository Horizons-Games/Axolotl-Engine, pull requests merged in 2023-09, with the labels that each got.

#672 feat : Graphics/script&perf
  Game/Scripts/AnimatedLine.cpp
  Game/Scripts/AnimatedLine.h
  Game/Scripts/AnimatedTexture.cpp
  Game/Scripts/AnimatedTexture.h
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/Windows/SubWindows/WindowFrustum.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleDebugDraw.cpp
  Source/Modules/ModuleDebugDraw.h
  Source/Modules/ModulePhysics.cpp
Labels: graphics

#691 Graphics/light culling
  Source/Modules/ModuleRender.cpp
  Source/Shaders/deferred_lighting_fragment.glsl
Labels: graphics

#690 fix[particles]: Fixed particles with a very small duration not being deleted
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleBase.h
  Source/DataModels/Scene/Scene.cpp
  Source/Modules/ModuleRender.cpp
  Source/Shaders/deferred_lighting_fragment.glsl
Labels: graphics

#696 feat[SSAO]: Screen Space Ambient Occlusion
  Source/DataModels/GBuffer/GBuffer.cpp
  Source/DataModels/GBuffer/GBuffer.h
  Source/DataModels/PostProcess/SSAO.cpp
  Source/DataModels/PostProcess/SSAO.h
  Source/DataModels/Program/Program.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/render_clip_space_vertex.glsl
  Source/Shaders/ssao_fragment.glsl
Labels: graphics

#698 perf/refactor: final boss code improvements
  Game/Scripts/BossChargeAttackScript.cpp
  Game/Scripts/BossMissilesAttackScript.cpp
  Game/Scripts/BossShieldAttackScript.cpp
  Game/Scripts/BossShieldAttackScript.h
  Game/Scripts/EnemyClass.cpp
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/EnemyDroneScript.cpp
  Game/Scripts/EnemyVenomiteScript.cpp
  Game/Scripts/FinalBossScript.cpp
  Game/Scripts/FinalBossScript.h
  Game/Scripts/PlayerForceUseScript.cpp
Labels: gameplay

#699 feat[SSAO]: Screen Space Ambient Occlusion
  README.md
  Source/DataModels/GBuffer/GBuffer.cpp
  Source/DataModels/GBuffer/GBuffer.h
  Source/DataModels/PostProcess/SSAO.cpp
  Source/DataModels/PostProcess/SSAO.h
  Source/DataModels/Program/Program.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/render_clip_space_vertex.glsl
  Source/Shaders/ssao_fragment.glsl
Labels: graphics

#701 feat[SCM]: Cascade Shadow Maps
  Game/Assets/Scenes/shadow_testing.axolotl
  README.md
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/PostProcess/SSAO.cpp
  Source/DataModels/Program/Program.cpp
  Source/DataModels/Program/Program.h
  Source/DataModels/Render/Shadows.cpp
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Scene/Scene.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/Common/Structs/cascade_light_matrices.glsl
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/gaussian_blur_3d_fragment.glsl
  Source/Shaders/gaussian_blur_3d_geometry.glsl
  Source/Shaders/render_clip_space_vertex_3d.glsl
  Source/Shaders/shadow_depth_variance.glsl
  Source/Shaders/shadow_map_geometry.glsl
  Source/Shaders/shadow_map_vertex.glsl
Labels: graphics

#704 feat[particles]: Now you can change for a particle system to follow its emitter
  Game/Assets/ParticleSystem/AlluraLightFinisher.particle
  Game/Assets/ParticleSystem/BigDrop.particle
  Game/Assets/ParticleSystem/BlinkBottle.particle
  Game/Assets/ParticleSystem/DetectParticle.particle
  Game/Assets/ParticleSystem/DroneDamaged.particle
  Game/Assets/ParticleSystem/DroneLaser.particle
  Game/Assets/ParticleSystem/DronePreShotVFX.particle
  Game/Assets/ParticleSystem/DroneSeekExplosion.particle
  Game/Assets/ParticleSystem/Drops2.particle
  Game/Assets/ParticleSystem/EnemyExclamation.particle
  Game/Assets/ParticleSystem/ExplosionDrone.particle
  Game/Assets/ParticleSystem/JumpFinisherAreaParticles.particle
  Game/Assets/ParticleSystem/LightFinisherBulletParticles.particle
  Game/Assets/ParticleSystem/MiniBossEnergyBeamPreShot.particle
  Game/Assets/ParticleSystem/MiniBossEnergyBeamShot.particle
  Game/Assets/ParticleSystem/MiniBossTwoEnergyBeam.particle
  Game/Assets/ParticleSystem/MiniBossTwoEnergyBeamDeactiavtion.particle
  Game/Assets/ParticleSystem/NewSpark1.particle
  Game/Assets/ParticleSystem/RadiatedWater.particle
  Game/Assets/ParticleSystem/ShotCollision.particle
  Game/Assets/ParticleSystem/SoundWave.particle
  Game/Assets/ParticleSystem/SparkLight.particle
  Game/Assets/ParticleSystem/Sparks1.particle
  Game/Assets/ParticleSystem/TestParticles.particle
  Game/Assets/ParticleSystem/VenomitePreShoot.particle
  Game/Assets/ParticleSystem/VenomiteShoot_VFX.particle
  Game/Assets/ParticleSystem/WaterSplash.particle
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleBase.h
  Source/DataModels/ParticleSystem/ModulePosition.cpp
  Source/FileSystem/Importers/ParticleSystemImporter.cpp
Labels: graphics

#703 feat[SCM]: Cascade Shadow Maps
  Game/Assets/Scenes/shadow_testing.axolotl
  README.md
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/PostProcess/SSAO.cpp
  Source/DataModels/Program/Program.cpp
  Source/DataModels/Program/Program.h
  Source/DataModels/Render/Shadows.cpp
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Scene/Scene.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/Common/Structs/cascade_light_matrices.glsl
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/gaussian_blur_3d_fragment.glsl
  Source/Shaders/gaussian_blur_3d_geometry.glsl
  Source/Shaders/render_clip_space_vertex_3d.glsl
  Source/Shaders/shadow_depth_variance.glsl
  Source/Shaders/shadow_map_geometry.glsl
  Source/Shaders/shadow_map_vertex.glsl
Labels: graphics

#705 Feat: ComponentLine Use Alpha
  External/ImGui/imgui_color_gradient.cpp
  External/ImGui/imgui_color_gradient.h
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/Components/ComponentTrail.cpp
  Source/Shaders/component_line_fragment.glsl
  Source/Shaders/component_line_vertex.glsl
Labels: graphics

#707 Fix: Bix and Allura Normal Combo Attack Animation State Machine
  Game/Assets/Materials/MiniBossTwoEnergyBeam.mat
  Game/Assets/Materials/MiniBossTwoEnergyBeam.mat.meta
  Game/Assets/NavMesh/GameplayMiniBoss2.nav
  Game/Assets/NavMesh/GameplayMiniBoss2.nav.meta
  Game/Assets/Scenes/Gameplay_MiniBoss2.axolotl
  Game/Assets/Scenes/Gameplay_MiniBoss2_with_allura.axolotl
  Game/Assets/StateMachine/AlluraAnimController.state
  Game/Assets/StateMachine/AlluraAnimController.state.meta
  Game/Assets/StateMachine/BixAnimController.state
  Game/Assets/StateMachine/BixAnimController.state.meta
  Game/Scripts/BoostOfEnergy.cpp
  Game/Scripts/ComboManager.cpp
  Game/Scripts/PlayerAttackScript.cpp
  Game/Scripts/PlayerAttackScript.h
  Game/Scripts/PlayerMoveScript.cpp
  Source/DataModels/Animation/AnimationController.cpp
  Source/DataModels/Animation/AnimationController.h
Labels: gameplay

#718 feat[SCM]: Logarithmic split & fixed issues with particle instances
  Source/DataModels/Components/ComponentParticleSystem.cpp
  Source/DataModels/Components/ComponentParticleSystem.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.h
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleBase.h
  Source/DataModels/ParticleSystem/ModuleColor.cpp
  Source/DataModels/ParticleSystem/ModuleColor.h
  Source/DataModels/ParticleSystem/ModulePosition.cpp
  Source/DataModels/ParticleSystem/ModulePosition.h
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.h
  Source/DataModels/ParticleSystem/ModuleRotation.cpp
  Source/DataModels/ParticleSystem/ModuleRotation.h
  Source/DataModels/ParticleSystem/ModuleSize.cpp
  Source/DataModels/ParticleSystem/ModuleSize.h
  Source/DataModels/ParticleSystem/ModuleSpawn.cpp
  Source/DataModels/ParticleSystem/ModuleSpawn.h
  Source/DataModels/Render/Shadows.cpp
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.h
  Source/Shaders/logarithmic_split.glsl
Labels: graphics

#730 refactor[particles]: refactored particles so they now work propertly
  Source/DataModels/Components/ComponentParticleSystem.cpp
  Source/DataModels/Components/ComponentParticleSystem.h
  Source/DataModels/ParticleSystem/EmitterInstance.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.h
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleBase.h
  Source/DataModels/ParticleSystem/ModuleColor.cpp
  Source/DataModels/ParticleSystem/ModuleColor.h
  Source/DataModels/ParticleSystem/ModulePosition.cpp
  Source/DataModels/ParticleSystem/ModulePosition.h
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.h
  Source/DataModels/ParticleSystem/ModuleRotation.cpp
  Source/DataModels/ParticleSystem/ModuleRotation.h
  Source/DataModels/ParticleSystem/ModuleSize.cpp
  Source/DataModels/ParticleSystem/ModuleSize.h
  Source/DataModels/ParticleSystem/ModuleSpawn.cpp
  Source/DataModels/ParticleSystem/ModuleSpawn.h
  Source/DataModels/ParticleSystem/ParticleEmitter.cpp
  Source/DataModels/ParticleSystem/ParticleEmitter.h
  Source/DataModels/ParticleSystem/ParticleModule.cpp
  Source/DataModels/ParticleSystem/ParticleModule.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentParticle.cpp
Labels: graphics

#732 Feat[VSM]: Reduced light bleeding & Modifiable z offset
  Game/Assets/Scenes/shadow_testing.axolotl
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/Components/ComponentDirLight.h
  Source/DataModels/Render/Shadows.cpp
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
  Source/Modules/ModuleRender.cpp
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/gaussian_blur_3d_geometry.glsl
  Source/Shaders/logarithmic_split.glsl
  Source/Shaders/shadow_map_geometry.glsl
Labels: graphics

#738 Fix : ComponentLine copy fixed
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/Components/ComponentLine.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/Scene/Scene.cpp
Labels: graphics

#742 feat: copy constructor trail
  Game/Assets/Scenes/TrailTest.axolotl
  Source/DataModels/Components/ComponentAreaLight.cpp
  Source/DataModels/Components/ComponentRender.cpp
  Source/DataModels/Components/ComponentTrail.cpp
  Source/DataModels/Components/ComponentTrail.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.cpp
Labels: graphics

#737 feat: Modifications to Final Boss so behavior and different attacks are correct with ComponentAgent
  Game/Scripts/FinalBossScript.cpp
Labels: gameplay

#745 fix: Player movement while hacking
  Game/Scripts/PlayerHackingUseScript.cpp
  Game/Scripts/PlayerHackingUseScript.h
  Game/Scripts/PlayerManagerScript.cpp
  Game/Scripts/PlayerMoveScript.cpp
Labels: gameplay

#733 feat[Shadows]: Reduced light bleeding & Modifiable z offset / fix[particles]: refactored particles so they now work with instanced info
  External/ImGui/imgui_color_gradient.cpp
  External/ImGui/imgui_color_gradient.h
  Game/Assets/Scenes/TrailTest.axolotl
  Game/Assets/Scenes/shadow_testing.axolotl
  Source/DataModels/Components/ComponentAreaLight.cpp
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/Components/ComponentDirLight.h
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/Components/ComponentLine.h
  Source/DataModels/Components/ComponentParticleSystem.cpp
  Source/DataModels/Components/ComponentParticleSystem.h
  Source/DataModels/Components/ComponentRender.cpp
  Source/DataModels/Components/ComponentTrail.cpp
  Source/DataModels/Components/ComponentTrail.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.cpp
  Source/DataModels/ParticleSystem/EmitterInstance.h
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleBase.h
  Source/DataModels/ParticleSystem/ModuleColor.cpp
  Source/DataModels/ParticleSystem/ModuleColor.h
  Source/DataModels/ParticleSystem/ModulePosition.cpp
  Source/DataModels/ParticleSystem/ModulePosition.h
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.h
  Source/DataModels/ParticleSystem/ModuleRotation.cpp
  Source/DataModels/ParticleSystem/ModuleRotation.h
  Source/DataModels/ParticleSystem/ModuleSize.cpp
  Source/DataModels/ParticleSystem/ModuleSize.h
  Source/DataModels/ParticleSystem/ModuleSpawn.cpp
  Source/DataModels/ParticleSystem/ModuleSpawn.h
  Source/DataModels/ParticleSystem/ParticleEmitter.cpp
  Source/DataModels/ParticleSystem/ParticleEmitter.h
  Source/DataModels/ParticleSystem/ParticleModule.cpp
  Source/DataModels/ParticleSystem/ParticleModule.h
  Source/DataModels/Render/Shadows.cpp
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentDirLight.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentParticle.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTrail.h
  Source/Modules/ModuleRender.cpp
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/gaussian_blur_3d_geometry.glsl
  Source/Shaders/logarithmic_split.glsl
  Source/Shaders/particle_fragment.glsl
  Source/Shaders/shadow_map_geometry.glsl
Labels: graphics

#746 fix: Elevator script
  Game/Scripts/ElevatorCore.cpp
  Game/Scripts/ElevatorCore.h
  Source/Engine.vcxproj.filters
Labels: gameplay

#755 feat: Light culling
  External/ExternalDependencies.vcxproj
  External/ExternalDependencies.vcxproj.filters
  External/ParShapes/par_shapes.h
  Source/Auxiliar/SceneLoader.cpp
  Source/DataModels/Components/ComponentAreaLight.cpp
  Source/DataModels/Components/ComponentAreaLight.h
  Source/DataModels/Components/ComponentLight.h
  Source/DataModels/Components/ComponentPointLight.cpp
  Source/DataModels/Components/ComponentPointLight.h
  Source/DataModels/Components/ComponentSpotLight.cpp
  Source/DataModels/Components/ComponentSpotLight.h
  Source/DataModels/Components/ComponentTransform.cpp
  Source/DataModels/Render/LightPass.cpp
  Source/DataModels/Render/LightPass.h
  Source/DataModels/Render/Shadows.cpp
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Resources/ResourceMesh.cpp
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/lightCulling_fs.glsl
  Source/Shaders/lightCulling_vs.glsl
  Source/Shaders/metallic_fragment.glsl
  Source/Shaders/specular_fragment.glsl
Labels: graphics

#762 fix: Mesh Effect bugs
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/HealthSystem.h
  Game/Scripts/PlayerDeathScript.cpp
Labels: graphics, gameplay

#758 fix: dash integration fixes
  Game/Assets/Scenes/Gameplay_TrialAllura.axolotl
  Game/Assets/StateMachine/AlluraAnimController.state
  Game/Assets/StateMachine/BixAnimController.state
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/PlayerAttackScript.cpp
  Game/Scripts/PlayerAttackScript.h
  Game/Scripts/PlayerHackingUseScript.cpp
  Game/Scripts/PlayerJumpScript.cpp
  Game/Scripts/PlayerJumpScript.h
  Game/Scripts/PlayerManagerScript.cpp
  Game/Scripts/PlayerMoveScript.cpp
  Game/Scripts/PlayerMoveScript.h
Labels: gameplay

#759 feat: Elevator behaviour
  Game/Scripts/ActivationLogic.cpp
  Game/Scripts/ActivationLogic.h
  Game/Scripts/ElevatorCore.cpp
  Game/Scripts/ElevatorCore.h
Labels: gameplay
