Repository Horizons-Games/Axolotl-Engine, pull requests merged in 2023-11, with the labels that each got.

#882 fix&refactor: powerup tutorial
  Game/Scripts/CombatTutorial.cpp
  Game/Scripts/CombatTutorial.h
Labels: gameplay

#883 fix: Boss charge attack
  Game/Scripts/BossChargeAttackScript.cpp
  Game/Scripts/CameraBossControllerScript.cpp
Labels: gameplay

#885 fix: more boss issues
  Game/Scripts/BossChargeAttackScript.cpp
  Game/Scripts/BossChargeAttackScript.h
  Game/Scripts/BossMissilesAttackScript.cpp
  Game/Scripts/BossMissilesAttackScript.h
  Game/Scripts/BossShieldScript.cpp
  Game/Scripts/ShockWaveAttackScript.cpp
  Game/Scripts/ShockWaveAttackScript.h
Labels: gameplay

#889 Feat: Missions wait for the previous mission to disappear
  Game/Assets/Textures/CombatTut9.png
  Game/Assets/Textures/CombatTut9.png.meta
  Game/Assets/Textures/Text Voice Switch 6.png
  Game/Assets/Textures/Text Voice Switch 6.png.meta
  Game/Scripts/UIImageDisplacementControl.cpp
  Game/Scripts/UIImageDisplacementControl.h
  Game/Scripts/UIMissionTrigger.cpp
Labels: UI/UX

#891 feat: added debugging for graphic features in game mode
  Source/DataModels/Render/Shadows.h
  Source/DataModels/Windows/WindowDebug.cpp
  Source/Modules/ModuleRender.h
Labels: graphics, engine

#897 chore: adapted gaussian blur
  Source/Shaders/gaussian_blur.glsl
Labels: bug, graphics

#899 fix: fade out with reflection
  Game/Scripts/MeshEffect.cpp
Labels: bug, graphics, gameplay
