Repository Horizons-Games/Axolotl-Engine, pull requests merged in 2023-10, with the labels that each got.

#768 fix: doublejump afterattack animation
  Game/Assets/StateMachine/AlluraAnimController.state
  Game/Assets/StateMachine/BixAnimController.state
Labels: gameplay

#734 feat: Use skybox as cubemap
  Source/DataModels/Components/ComponentSkybox.cpp
  Source/DataModels/Components/ComponentSkybox.h
  Source/DataModels/Cubemap/Cubemap.cpp
  Source/DataModels/Cubemap/Cubemap.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentSkybox.cpp
  Source/Modules/ModuleRender.cpp
Labels: graphics

#775 fix: load scenes without skybox
  Source/Modules/ModuleRender.cpp
Labels: graphics

#753 feat: rumble on jump attack
  Game/Scripts/PlayerAttackScript.cpp
Labels: gameplay

#787 fix: Hacking while switching players
  Game/Scripts/PlayerHackingUseScript.cpp
  Game/Scripts/PlayerManagerScript.cpp
  Game/Scripts/PlayerManagerScript.h
Labels: gameplay

#789 fix[SceneLoad]: fixed memory leak in load scene async
  Source/Auxiliar/SceneLoader.cpp
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Resources/ResourceTexture.cpp
  Source/FileSystem/ModuleResources.cpp
  Source/FileSystem/ModuleResources.h
Labels: graphics, engine

#788 perf: Collision detection improved
  Source/Modules/ModulePhysics.cpp
Labels: physics

#790 fix: add and remove from dynamics vector
  Source/DataModels/Components/ComponentRigidBody.cpp
  Source/DataModels/Components/ComponentRigidBody.h
  Source/Modules/ModulePhysics.cpp
  Source/Modules/ModulePhysics.h
Labels: physics

#778 feat: Improve combo system
  Game/Scripts/PlayerAttackScript.cpp
  Game/Scripts/PlayerAttackScript.h
Labels: gameplay

#731 feat: reflections using local IBL
  Game/Assets/Scenes/[DO NOT DELETE]Graphics testing.axolotl
  Source/Auxiliar/SceneLoader.cpp
  Source/DataModels/Batch/BatchManager.cpp
  Source/DataModels/Batch/BatchManager.h
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Components/Component.h
  Source/DataModels/Components/ComponentAreaLight.cpp
  Source/DataModels/Components/ComponentAreaLight.h
  Source/DataModels/Components/ComponentAudioListener.cpp
  Source/DataModels/Components/ComponentAudioListener.h
  Source/DataModels/Components/ComponentAudioSource.cpp
  Source/DataModels/Components/ComponentAudioSource.h
  Source/DataModels/Components/ComponentLight.h
  Source/DataModels/Components/ComponentLocalIBL.cpp
  Source/DataModels/Components/ComponentLocalIBL.h
  Source/DataModels/Components/ComponentPointLight.cpp
  Source/DataModels/Components/ComponentPointLight.h
  Source/DataModels/Components/ComponentRigidBody.cpp
  Source/DataModels/Components/ComponentRigidBody.h
  Source/DataModels/Components/ComponentScript.cpp
  Source/DataModels/Components/ComponentScript.h
  Source/DataModels/Components/ComponentSkybox.cpp
  Source/DataModels/Components/ComponentSkybox.h
  Source/DataModels/Components/ComponentSpotLight.cpp
  Source/DataModels/Components/ComponentSpotLight.h
  Source/DataModels/Components/ComponentTrail.cpp
  Source/DataModels/Components/ComponentTransform.cpp
  Source/DataModels/Components/ComponentTransform.h
  Source/DataModels/Components/UI/ComponentButton.cpp
  Source/DataModels/Components/UI/ComponentButton.h
  Source/DataModels/Cubemap/Cubemap.cpp
  Source/DataModels/Cubemap/Cubemap.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/GameObject/GameObject.h
  Source/DataModels/Resources/ResourceMaterial.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
  Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/ComponentWindow.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLocalIBL.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLocalIBL.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/Common/Functions/common_functions.glsl
  Source/Shaders/Common/Functions/pbr_functions.glsl
  Source/Shaders/Common/Structs/local_IBL.glsl
  Source/Shaders/cubemap_vertex.glsl
  Source/Shaders/deferred_lighting_fragment.glsl
Labels: graphics

#752 feat[UI/HUD]: Combo System visuals
  Game/Assets/Scenes/HUD_Combo.axolotl
  Game/Assets/Textures/Group 124.png
  Game/Assets/Textures/Group 124.png.meta
  Game/Assets/Textures/UI_BETA_HUD_COMBOSYSTEM_JUMPATTACK.png
  Game/Assets/Textures/UI_BETA_HUD_COMBOSYSTEM_JUMPATTACK.png.meta
  Game/Assets/Textures/UI_BETA_HUD_COMBOSYSTEM_SHINYHOVER.png
  Game/Assets/Textures/UI_BETA_HUD_COMBOSYSTEM_SHINYHOVER.png.meta
  Game/Assets/Textures/UI_HUD_Barra.png
  Game/Assets/Textures/UI_HUD_Barra.png.meta
  Game/Assets/Textures/UI_HUD_Barra_nofill.png
  Game/Assets/Textures/UI_HUD_Barra_nofill.png.meta
  Game/Assets/Textures/UI_HUD_ComboBck.png
  Game/Assets/Textures/UI_HUD_ComboBck.png.meta
  Game/Assets/Textures/UI_HUD_ComboFill.png
  Game/Assets/Textures/UI_HUD_ComboFill.png.meta
  Game/Assets/Textures/UI_HUD_X.png
  Game/Assets/Textures/UI_HUD_X.png.meta
  Game/Assets/Textures/UI_HUD_Y.png
  Game/Assets/Textures/UI_HUD_Y.png.meta
  Game/Scripts/ComboManager.cpp
  Game/Scripts/LightAttackBullet.cpp
  Game/Scripts/UIComboManager.cpp
  Game/Scripts/UIComboManager.h
  Source/DataModels/Components/UI/ComponentImage.cpp
Labels: UI/UX

#818 feat: new controls gamepad image
  Game/Assets/Scenes/00_MainMenu_VS3.axolotl
  Game/Assets/Textures/UI_HUD_BETA_Controller_White.png
  Game/Assets/Textures/UI_HUD_BETA_Controller_White.png.meta
Labels: UI/UX

#806 fix: gameplay bix allura death
  Game/Assets/StateMachine/BixAnimController.state
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/PlayerAttackScript.cpp
  Game/Scripts/PlayerDeathScript.cpp
  Game/Scripts/PlayerManagerScript.cpp
Labels: gameplay

#826 fix: gameplay bix & allura death
  Game/Assets/StateMachine/BixAnimController.state
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/PlayerAttackScript.cpp
  Game/Scripts/PlayerDeathScript.cpp
  Game/Scripts/UIGameManager.cpp
Labels: gameplay

#812 feat: Options gamepad controls (DPAD)
  Game/Scripts/UIOptionsMenu.cpp
  Source/Modules/ModuleUI.cpp
Labels: UI/UX

#814 refactor: UI options
  Game/Scripts/UIOptionsMenu.cpp
  Game/Scripts/UIOptionsMenu.h
Labels: UI/UX

#836 fix: NPCs cantina
  Game/Scripts/CantinaNPCAnimationManager.cpp
Labels: gameplay

#853 fix: drone and venomite death
  Game/Assets/StateMachine/VenomiteAnimController.state
  Game/Scripts/BossShieldAttackScript.cpp
  Game/Scripts/EnemyDroneScript.cpp
  Game/Scripts/EnemyVenomiteScript.cpp
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/MeleeHeavyAttackBehaviourScript.cpp
  Game/Scripts/MeleeHeavyAttackBehaviourScript.h
Labels: gameplay

#865 fix: Miniboss2 move with shield and slide over the floor seeking
  Game/Assets/StateMachine/MiniBoss2AnimController.state
  Game/Scripts/BossShieldAttackScript.cpp
  Game/Scripts/EnemyMiniBossTwo.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.h
Labels: gameplay

#872 Fix: Stuck in Dash and repeating DoubleJumps anims
  Game/Assets/StateMachine/BixAnimController.state
  Game/Scripts/PlayerJumpScript.cpp
  Game/Scripts/PlayerJumpScript.h
Labels: gameplay

#876 fix: miniboss 2 freeze
  Game/Scripts/BossShieldAttackScript.cpp
  Game/Scripts/BossShieldAttackScript.h
  Game/Scripts/EnemyMiniBossTwo.cpp
Labels: gameplay
