Repository Horizons-Games/Axolotl-Engine, pull requests merged in 2023-07, with the labels that each got.

#569 feat: resources window docking
  Source/Modules/ModuleEditor.cpp
Labels: qol

#547 refactor: open scripts with a button
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
  Source/Modules/ModuleEditor.cpp
Labels: qol

#576 feat: open script with double click, but ignore clicks on widgets
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.h
Labels: qol

#536 refactor: unify raycast filter methods
  Source/Physics/Physics.cpp
  Source/Physics/Physics.h
Labels: physics

#572 fix: stop Bix movement and allow for the death screen to load
  Game/Scripts/PlayerDeathScript.cpp
Labels: gameplay

#582 Feat: Entity Detection and linked with Bix Attack
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/EntityDetection.cpp
  Game/Scripts/EntityDetection.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay

#579 feat[WIP]: bloom & tone mapping
  Game/Assets/Materials/Default.mat.meta
  Source/DataModels/GBuffer/GBuffer.h
  Source/Modules/ModuleInput.cpp
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/Common/Functions/pbr_functions.glsl
  Source/Shaders/Common/Uniforms/lights_uniform.glsl
  Source/Shaders/color_correction_fragment.glsl
  Source/Shaders/deferred_lighting_fragment.glsl
  Source/Shaders/environment_BRDF_fragment.glsl
  Source/Shaders/environment_BRDF_vertex.glsl
  Source/Shaders/gBuffer_Metallic_fs.glsl
  Source/Shaders/gBuffer_Specular_fs.glsl
  Source/Shaders/gaussian_blur_fragment.glsl
  Source/Shaders/metallic_fragment.glsl
  Source/Shaders/render_clip_space_vertex.glsl
  Source/Shaders/skybox_fragment.glsl
  Source/Shaders/specular_fragment.glsl
Labels: graphics

#529 feat: add search bar to WindowHierarchy
  Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
  Source/DataModels/Windows/EditorWindows/WindowHierarchy.h
Labels: qol

#588 feat : component line
  External/ExternalDependencies.vcxproj
  External/ExternalDependencies.vcxproj.filters
  External/ImGui/imgui_bezier.cpp
  External/ImGui/imgui_bezier.h
  External/ImGui/imgui_internal.h
  Game/Assets/Scenes/test.axolotl
  Game/Assets/Textures/beam.tga
  Game/Assets/Textures/beam.tga.meta
  Game/Scripts/AnimatedTexture.cpp
  Game/Scripts/AnimatedTexture.h
  Source/DataModels/Components/Component.h
  Source/DataModels/Components/ComponentLine.cpp
  Source/DataModels/Components/ComponentLine.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/Program/Program.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowLineTexture.cpp
  Source/DataModels/Windows/EditorWindows/ImporterWindows/WindowLineTexture.h
  Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
  Source/DataModels/Windows/EditorWindows/WindowInspector.h
  Source/DataModels/Windows/SubWindows/ComponentWindows/ComponentWindow.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentLine.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Enums/ComponentType.h
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Shaders/component_line_fragment.glsl
  Source/Shaders/component_line_vertex.glsl
Labels: graphics

#581 feat: add enemy parent class to unify certain functions
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Scripts/DebugGame.cpp
  Game/Scripts/DebugGame.h
  Game/Scripts/EnemyClass.cpp
  Game/Scripts/EnemyClass.h
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/EnemyDroneScript.cpp
  Game/Scripts/EnemyDroneScript.h
  Game/Scripts/EnemyVenomiteScript.cpp
  Game/Scripts/EnemyVenomiteScript.h
  Game/Scripts/MeleeHeavyAttackBehaviourScript.cpp
  Game/Scripts/MeleeHeavyAttackBehaviourScript.h
  Game/Scripts/PlayerForceAttackScript.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay

#584 fix: Stop Bix steps sound when dying
  Game/Scripts/PlayerDeathScript.cpp
  Game/Scripts/PlayerDeathScript.h
  Game/Scripts/PlayerMoveScript.cpp
Labels: gameplay

#583 fix: powerups correctly spawn in the enemy location
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Scripts/DebugGame.cpp
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/MeleeFastAttackBehaviourScript.cpp
  Game/Scripts/PowerUpLogicScript.cpp
  Game/Scripts/PowerUpLogicScript.h
  Game/Scripts/RangedFastAttackBehaviourScript.cpp
  Game/Scripts/RangedFastAttackBullet.cpp
  Source/DataModels/Components/ComponentAnimation.cpp
  Source/DataModels/Components/ComponentMeshCollider.cpp
  Source/DataModels/Components/ComponentRigidBody.cpp
  Source/DataModels/Components/ComponentTransform.cpp
  Source/DataModels/Components/ComponentTransform.h
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Windows/EditorWindows/WindowScene.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform.cpp
Labels: gameplay

#590 feat: Collisions detection request
  Source/Modules/ModulePhysics.cpp
  Source/Modules/ModulePhysics.h
Labels: physics

#599 feat: raise exception in scripts if GetComponent would return nullptr
  Source/Auxiliar/ComponentNotFoundException.cpp
  Source/Auxiliar/ComponentNotFoundException.h
  Source/DataModels/Batch/GeometryBatch.cpp
  Source/DataModels/Camera/CameraEngine.cpp
  Source/DataModels/Components/ComponentAnimation.cpp
  Source/DataModels/Components/ComponentAreaLight.cpp
  Source/DataModels/Components/ComponentAudioListener.cpp
  Source/DataModels/Components/ComponentAudioSource.cpp
  Source/DataModels/Components/ComponentBreakable.cpp
  Source/DataModels/Components/ComponentCamera.cpp
  Source/DataModels/Components/ComponentCameraSample.cpp
  Source/DataModels/Components/ComponentDirLight.cpp
  Source/DataModels/Components/ComponentMeshCollider.cpp
  Source/DataModels/Components/ComponentMeshRenderer.cpp
  Source/DataModels/Components/ComponentPointLight.cpp
  Source/DataModels/Components/ComponentRigidBody.cpp
  Source/DataModels/Components/ComponentScript.cpp
  Source/DataModels/Components/ComponentScript.h
  Source/DataModels/Components/ComponentSpotLight.cpp
  Source/DataModels/Components/ComponentTransform.cpp
  Source/DataModels/Components/UI/ComponentImage.cpp
  Source/DataModels/Components/UI/ComponentSlider.cpp
  Source/DataModels/Components/UI/ComponentTransform2D.cpp
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/GameObject/GameObject.h
  Source/DataModels/GameObject/GameObject.inl
  Source/DataModels/ParticleSystem/ModuleBase.cpp
  Source/DataModels/ParticleSystem/ModuleRenderer.cpp
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Windows/EditorWindows/WindowConsole.cpp
  Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp
  Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
  Source/DataModels/Windows/EditorWindows/WindowScene.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentImage.cpp
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentTransform.cpp
  Source/DataStructures/Quadtree.cpp
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
  Source/Modules/ModulePlayer.cpp
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleScene.cpp
  Source/Modules/ModuleUI.cpp
  Source/Physics/Physics.cpp
  Source/Scripting/RegisterFieldMacros.h
Labels: qol

#601 fix[gameplay]: enemies range attacks
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Assets/Scenes/NewVenomitePrefab.axolotl
  Game/Scripts/RangedFastAttackBehaviourScript.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.h
  Game/Scripts/RangedFastAttackBullet.cpp
  Game/Scripts/RangedFastAttackBullet.h
  Source/DataModels/GameObject/GameObject.cpp
  Source/DataModels/Windows/EditorWindows/WindowInspector.cpp
Labels: gameplay

#589 feat/perf: Kawase dual filtering
  Source/Modules/ModuleProgram.cpp
  Source/Modules/ModuleProgram.h
  Source/Modules/ModuleRender.cpp
  Source/Modules/ModuleRender.h
  Source/Shaders/color_correction_fragment.glsl
  Source/Shaders/gaussian_blur_fragment.glsl
  Source/Shaders/kawase_down_fragment.glsl
  Source/Shaders/kawase_up_fragment.glsl
Labels: graphics

#604 fix: component line serialization game mode
  Source/DataModels/Components/ComponentLine.cpp
Labels: bug, graphics

#607 fix: stop enemies rotation and movement once they are dead among other things
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewDronePrefab.axolotl
  Game/Assets/Scenes/NewVenomitePrefab.axolotl
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/EnemyDeathScript.h
  Game/Scripts/EnemyVenomiteScript.cpp
  Game/Scripts/EntityDetection.cpp
  Game/Scripts/EntityDetection.h
  Game/Scripts/PlayerDeathScript.cpp
Labels: gameplay

#610 feat: sort script constructors by name in window
  Source/DataModels/Windows/SubWindows/ComponentWindows/WindowComponentScript.cpp
Labels: qol

#597 Feat: Combo system
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/StateMachine/BixAnimController.state
  Game/Assets/Textures/button_xbox_digital_x_4.png
  Game/Assets/Textures/button_xbox_digital_x_4.png.meta
  Game/Assets/Textures/button_xbox_digital_y_4.png
  Game/Assets/Textures/button_xbox_digital_y_4.png.meta
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/ComboManager.cpp
  Game/Scripts/ComboManager.h
  Game/Scripts/PlayerJumpScript.cpp
  Game/Scripts/PlayerJumpScript.h
  Game/Scripts/PlayerManagerScript.cpp
  Game/Scripts/PlayerManagerScript.h
  Game/Scripts/UIComboManager.cpp
  Game/Scripts/UIComboManager.h
  Source/DataModels/Components/ComponentRigidBody.cpp
  Source/DataModels/Scene/Scene.cpp
  Source/DataModels/Scene/Scene.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay

#612 feat: Allura jumping finisher
  Game/Assets/Scenes/GameplayFullTrial_VS3.axolotl
  Game/Assets/Scenes/NewBixPrefab.axolotl
  Game/Scripts/BixAttackScript.cpp
  Game/Scripts/BixAttackScript.h
  Game/Scripts/EnemyDeathScript.cpp
  Game/Scripts/EnemyDeathScript.h
  Game/Scripts/EntityDetection.cpp
  Game/Scripts/EntityDetection.h
  Game/Scripts/HealthSystem.cpp
  Game/Scripts/JumpFinisherArea.cpp
  Game/Scripts/JumpFinisherArea.h
  Game/Scripts/JumpFinisherAttack.cpp
  Game/Scripts/JumpFinisherAttack.h
  Game/Scripts/JumpFinisherAttackBullet.cpp
  Game/Scripts/JumpFinisherAttackBullet.h
  Game/Scripts/PlayerDeathScript.cpp
  Game/Scripts/RangedFastAttackBehaviourScript.cpp
  Game/Scripts/RangedFastAttackBullet.cpp
  Game/Scripts/RangedFastAttackBullet.h
  Source/Engine.vcxproj
  Source/Engine.vcxproj.filters
Labels: gameplay
